# Generated by Django 3.1.7 on 2021-05-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verser', '__first__'),
        ('notification', '0002_notification_user_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernotify', to='verser.customuser'),
        ),
    ]
